comet-ml/kangas

- backend/kangas/cli/viewer.py
- backend/kangas/datatypes/datagrid.py
- backend/kangas/server/computed_columns.py
- backend/kangas/server/queries.py
This PR extends the query language to allow accessing JSON array values. Requires any() or all() for filter.
Examples:
* `any([x.label == 'dog' for x in {"Image"}.overlays])` - images with dogs
* `all([x.label == 'person' for x in {"Image"}.overlays])` - images with only people (no other labels)
* `any([x.label in ["car", "bicycle"] for x in {"Image"}.overlays])` - images with cars or bicycles
* `any([x.label == "cat" or x.label == "dog" for x in {"Image"}.overlays])` - images with dogs or cats
* `any([x.label == "cat" for x in {"Image"}.overlays]) and any([x.label == "dog" for x in {"Image"}.overlays])` - images with dogs and cats
* `any([x.score  > 0.999 for x in {"Image"}.overlays])` - images with an annotation score greater than 0.999
> Extend query language to access JSON array values

- backend/kangas/server/computed_columns.py
- backend/kangas/server/queries.py
- backend/setup.py
This PR extends the query language to allow accessing JSON array values. Requires any() or all() for filter.
Examples:
* `any([x["label"] == 'dog' for x in {"Image"}.overlays])` - images with dogs
* `all([x["label"] == 'person' for x in {"Image"}.overlays])` - images with only people (no other labels)
* `any([x["label"] in ["car", "bicycle"] for x in {"Image"}.overlays])` - images with cars or bicycles
* `any([x["label"] == "cat" or x["label"] == "dog" for x in {"Image"}.overlays])` - images with dogs or cats
* `any([x["label"] == "cat" for x in {"Image"}.overlays]) and any([x["label"] == "dog" for x in {"Image"}.overlays])` - images with dogs and cats
* `any([x["score"]  > 0.999 for x in {"Image"}.overlays])` - images with an annotation score greater than 0.999
> Extend query language: access JSON arrays

- backend/kangas/server/handlers.py
- backend/kangas/server/queries.py
- backend/tests/unit/test_computed_columns.py
This PR breaks out the SQL total from the paged query.
At some point, we can deprecate /datagrid/query
> Add /datagrid/query-page and /datagrid/query-total endpoints

- examples/hugging_face/datagrids_with_hub/README.md
- examples/hugging_face/datagrids_with_hub/download_from_hub.py
- examples/hugging_face/datagrids_with_hub/predict.py
- examples/hugging_face/datagrids_with_hub/requirements.txt
- examples/hugging_face/datagrids_with_hub/upload_to_hub.py
- notebooks/Using_Kangas_Datagrids_with_the_Hugging_Face_Hub.ipynb
This PR:
1. Adds example scripts and a README to demonstrate how to upload and download datagrids to the Hugging Face Hub.
2. Adds an example Notebook to demonstrate how to download datagrids directly from the Hub.
> Add example for using DataGrid with the HF Hub

- examples/hugging_face/datagrids_with_hub/README.md
This PR:
1. Adds a link to a Colab Notebook Example on using DataGrids with the HF Hub.
> Add Colab link to HF Hub example README

- frontend/app/Settings/ReactAutoComplete.js
Adds some line-height so you can see the wavy line.
Before:
After:
> Add line-height to see wavy line

- frontend/app/DeferredComponent.js
- frontend/app/cells/image/ImageCanvas/ImageCanvas.module.scss
- frontend/app/cells/image/ImageCanvas/ImageCanvasCell.js
- frontend/app/cells/image/ImageCanvas/Output.js
- frontend/app/cells/image/ImageCanvas/OutputClient.js
- frontend/app/prefetch.js
- frontend/lib/fetchDatagrid.js
Occasionally, specific images will be drawn with mis-scaled labels when in grouped view. The issue is stems from the fact that images of certain dimensions will resize multiple times, and our resize-redraw loop had some nondeterministic execution order.
This breaks apart the steps of the resize-redraw loop to better control order. There seems to be some performance ding, which I'll be addressing in a separate issue next.
>  Draw labels with correct scale 

- frontend/app/Table/table.js
This fixes an issue when the backend returns the row object in a different order than what was expected.
> Table row order bug

- frontend/app/cells/boolean/GroupedBooleanCell.js
- frontend/app/cells/boolean/index.js
- frontend/app/cells/charts/category/CategoryClient.js
- frontend/app/cells/charts/histogram/Histogram.js
- frontend/app/cells/charts/histogram/HistogramClient.js
- frontend/app/cells/date/GroupedDateCell.js
- frontend/app/cells/date/index.js
- frontend/app/cells/float/GroupedFloatCell.js
- frontend/app/cells/float/index.js
- frontend/app/page.js
- frontend/app/perf/Imports.js
Currently, our lazy loading is not accurately reflecting what is and isn't in the viewport. This fixes that, rendering the initial columns via SSR and offloading the rest to client fetching, to be fetched as they scroll into view.
> Better lazy loading of histograms/categories

- frontend/app/cells/Cell.module.scss
Otherwise the header can get smaller than the cell. Why do we need min width?
> Revert grouped-cell min width

- frontend/app/cells/image/GroupedImageCell.js
- frontend/app/cells/image/ImageCanvas/ExpandedCanvasClientSide.js
- frontend/app/cells/image/ImageCanvas/ImageCanvasCell.js
- frontend/lib/fetchAssetMetadata.js
- frontend/package.json
Defers the metadata fetching for single image modals until they are loaded into view
> Prevent unnecessary metadata fetches in grouped view

- backend/kangas/datatypes/colormaps.py
- backend/kangas/datatypes/utils.py
- backend/kangas/server/queries.py
- frontend/lib/canvas.js
- frontend/lib/generateChartColor.js
Annotations are too useful, and so we want to see/use them as much as possible, if they can be drawn quickly. 
This PR adds the quick-drawing annotations to thumbnails: lines, regions, segmentation masks, metric masks, and bounding boxes. 
One consequence of this PR: I had to change the color mapping from text to colors slightly in order to replicate it in Python. The Javascript version relied on some esoteric aspects of Javascript (32-bit shifts, 64-bit max, etc).
After:
> Add annotations to thumbnails

- backend/kangas/datatypes/embedding.py
- backend/kangas/server/flask_server.py
- backend/kangas/server/queries.py
- frontend/app/cells/charts/histogram/Histogram.js
- frontend/app/cells/embedding/EmbeddingCellClient.js
- frontend/pages/api/embeddings-as-pca.js
Adds the color to the trace for scatter plots. But this makes 33% larger URLs for the thumbnail maker. So, had to create a way to make thumbnails directly.
> Get scatter color from trace; don't use /api/charts for large scatter plots

- backend/kangas/__init__.py
- backend/kangas/datatypes/__init__.py
- backend/kangas/datatypes/embedding.py
- backend/kangas/datatypes/image.py
- backend/kangas/datatypes/tensor.py
- frontend/lib/consts/cellMap.js
To avoid confusion with the JSON-based vector, rename Vector to kangas.Tensor().
> Rename Vector asset to Tensor

- frontend/app/cells/charts/Charts.module.scss
- frontend/app/cells/charts/category/CategoryClient.js
- frontend/app/cells/charts/histogram/HistogramClient.js
When you click on a histogram or category bar, copy to clipboard the criteria to select those items. You'll need to add to existing filter, if there is one. Can be used in filter or computed columns.
> Add copy-to-clipboard when click on histogram or category bar

- frontend/app/cells/boolean/GroupedBooleanCell.js
- frontend/app/cells/charts/category/Category.js
- frontend/app/cells/charts/category/CategoryClient.js
- frontend/app/cells/text/GroupedTextCell.js
When you click on a category chart bar, it sets the clipboard to be able to select the items in that bar. In order to create proper Python (to create proper SQL) you need to know whether the column values (groupBy and the specific column) are strings or not. To get this information, we get the metadata for the datagrid, and look at "type" to see if it "TEXT". If so, we put quotes around it, otherwise use the unquoted value.
For example, if you group on column target, and click on the category bar of row-id, it should produce the expression copied to the clipboard:
```
{"target"} == "malignant" and {"row-id"} == 19
```
Note that malignant is quoted, and 19 is not. We know how, because of the metadata.
> Fixed Category selection bug

- frontend/app/Polling.js
- frontend/app/cells/charts/category/Category.js
- frontend/app/cells/charts/category/CategoryClient.js
- frontend/app/cells/charts/histogram/Histogram.js
- frontend/app/cells/charts/histogram/HistogramClient.js
- frontend/app/cells/date/BaseDateCell.js
- frontend/lib/fetchAbout.js
- frontend/lib/fetchCategory.js
- frontend/lib/fetchDatagridTotal.js
Some queries don't have timestamps, and therefore cache their results without regard for updates to the underlying datagrid. This fixes that.
> Fix dynamic update bug

- frontend/app/Polling.js
- frontend/app/Settings/Buttons/RefreshButton.js
- frontend/app/Settings/MatrixSelectClient.js
- frontend/app/contexts/ModalContext.js
- frontend/app/contexts/ViewContext.js
- frontend/app/page.js
Previously, we stored the timestamp in the URL along with other parts of Kangas' state. We also used the updating of the timestamp URL query param as an implicit reload of the page. To remove the timestamp from the URL, we instead store the timestamp in the query object within ViewContext, and trigger reloads in our Polling component by calling window.reload() directly.
> Remove timestamp from URL

- frontend/app/Settings/FilterExpr.js
- frontend/app/Settings/index.js
In certain circumstances, the filter bar will flag a valid filter expression as invalid and prevent submission. This fixes the issue by removing an unnecessary check performed by the validator function.
> Fix debounce issue in filter bar

- backend/kangas/cli/server.py
Allows one to:
```
kangas server --rows=15 name.datagrid
```
> Set rows from command-line
