- backend/kangas/cli/viewer.py
- backend/kangas/datatypes/datagrid.py
- backend/kangas/server/computed_columns.py
- backend/kangas/server/queries.py
Reverts comet-ml/kangas#14
Performance hits.
> Revert "Extend query language to access JSON array values"

- examples/hugging_face/object_detection/README.md
- examples/hugging_face/object_detection/detect.py
- examples/hugging_face/object_detection/requirements.txt
This PR:
Adds an object detection tutorial using Hugging Face and Kangas
> Object Detection Example

- backend/kangas/server/computed_columns.py
- backend/kangas/server/queries.py
This PR adds if's to the list comprehension query language:
* `any([x["label"] for x in {"image"}.overlays if x["label"] in ["sink"]])` - use if to filter
* `any([x for x in {"image"} if 1 or 1/0])` - short circuit logic (doesn't crash here)
> Implement list comprehension ifs

- frontend/components/Cells/Image/Canvas.client.js
- frontend/components/Cells/Image/ImageCanvas.css
Adds a loading spinner to images in the canvas. This is a temporary fix before we migrate to Next 13.
> add loading spinner

- backend/kangas/datatypes/base.py
- backend/kangas/datatypes/datagrid.py
- backend/kangas/datatypes/image.py
- backend/kangas/datatypes/serialize.py
- backend/kangas/server/queries.py
This PR:
* Refactors dg.select() to use existing method
* fix limit in max column length from 100 to 10000
* allow limit to be None (return all)
* added lazy loading assets
* dg.select() deserializes assets
* all deserialized assets are lazy
> Refactor dg.select(); fix limit on max col len; allow limit to be None

- backend/kangas/cli/server.py
- backend/kangas/datatypes/base.py
- backend/kangas/datatypes/datagrid.py
- backend/tests/testlib.py
- backend/tests/unit/test_dataframe.py
no need to inherit from object
whitespace clean up
import sort
> python 3 tidyups

- backend/kangas/cli/server.py
- backend/kangas/server/__init__.py
- backend/kangas/server/handlers.py
This PR is designed to allow the tornado web server to run fetches in parallel.
> Parallel tornado

- backend/kangas/datatypes/image.py
This PR adds a flag to Image() to allow cv2 color ordering:
```python
from kangas import Image
import cv2
im = cv2.imread("FILENAME")
kangas_image = Image(im, color_order="bgr")
kangas_image.show()
```
> Added Image(color_order="bgr") for cv2 color format

- frontend/app/cells/float/GroupedFloatCell.js
> Typo in case of filename

- frontend/app/Table/table.js
- frontend/app/cells/Cell.module.scss
- frontend/app/cells/base.js
- frontend/app/cells/float/BaseFloatCell.js
- frontend/app/cells/float/index.js
- frontend/app/cells/image/BaseImageCell.js
- frontend/app/cells/image/index.js
- frontend/app/cells/json/JSONCell.js
- frontend/app/cells/text/BaseTextCell.js
- frontend/app/cells/text/index.js
1. Created an object with styling info (idx matches columns; may want this to be name-based)
2. Passed style down to be used in-line on columns
> Moved cell width and styling to table.js

- frontend/app/cells/text/BaseTextCell.js
- frontend/app/cells/text/index.js
- frontend/package.json
- frontend/yarn.lock
> Revert "Linkify text"

- backend/kangas/server/__init__.py
- backend/kangas/server/flask_server.py
- backend/kangas/server/translogger.py
Adds a simple Waitress implementation to replace the Flask dev server. This should clear up our problems on Windows.
@dsblank I initially was seeing a strange behavior where, after performing a group by on a large table, subsequent updates (changing datagrids, pages, etc.) were not processing. However, the issue suddenly resolved and I'm unable to reproduce, so it was perhaps a caching issue. Please let me know if you see anything similar :)
> Implement Waitress

- frontend/app/page.js
Otherwise, we get 10 rows of grouped data... too much!
> Set rows, if grouped

- backend/kangas/__init__.py
- backend/kangas/cli/server.py
- backend/kangas/utils.py
- frontend/config.js
1. Don't print new version on stdout
2. Separate backend/frontend protocol://host variables
> Separate backend from frontend HOST and PROTOCOL vars

- frontend/app/cells/image/BaseImageCell.js
- frontend/app/cells/image/ImageCanvas/Controls.js
- frontend/app/cells/image/ImageCanvas/ImageCanvas.module.scss
- frontend/app/cells/image/ImageCanvas/ImageCanvasCell.js
- frontend/app/contexts/CanvasContext.js
Reimplements the metadata accordion on the single image modal
> Add metadata to single image modal

- frontend/app/cells/base.js
- frontend/app/cells/image/index.js
- frontend/lib/fetchHistogram.js
> Treat target cells in group queries as ungrouped

- backend/kangas/datatypes/base.py
- backend/kangas/datatypes/image.py
- backend/kangas/datatypes/utils.py
- backend/kangas/server/queries.py
- backend/tests/unit/test_computed_columns.py
- frontend/app/Settings/index.js
- frontend/app/cells/image/ImageCanvas/Controls.js
- frontend/app/cells/image/ImageCanvas/ImageCanvas.module.scss
- frontend/app/cells/image/ImageCanvas/ImageCanvasCell.js
- frontend/app/cells/image/ImageCanvas/Mui.css
- frontend/app/cells/image/ImageCanvas/OutputClient.js
- frontend/app/page.js
- frontend/lib/canvas.js
- frontend/lib/createColormap.js
- frontend/lib/fetchStatus.js
- frontend/lib/generateChartColor.js
- frontend/lib/hooks/useLabels.js
- frontend/package.json
- frontend/pages/api/status.js
- frontend/yarn.lock
Adds:
1. lines - `image.add_line()`
2. markers - `image.add_marker()` - "raindrop" or "circle"
3. masks - `image.add_mask()` and `image.add_mask_metric()`
All annotations have labels and scores, and use the standard kangas UI. Metric masks will need more UI for additional control. Note that masks are generally designed for one per layer.
The masks will need some in-depth documentation.
> More annotations: masks, lines, and markers

- frontend/app/cells/Cell.module.scss
- frontend/app/cells/image/ImageCanvas/Controls.js
- frontend/app/cells/json/JSONCell.js
Not sure of the implications of moving this code to the client.
> Use JSON viewer in expanded cell

- backend/kangas/datatypes/datagrid.py
- frontend/app/cells/image/ImageCanvas/Controls.js
- frontend/app/cells/image/ImageCanvas/Label.js
- frontend/app/cells/image/ImageCanvas/OutputClient.js
- frontend/app/contexts/CanvasContext.js
- frontend/lib/canvas.js
- frontend/lib/tags.js
This PR adds the layer name to the labeling system for UI showing tagged annotations, and scores.
> Labels with layer names

- frontend/lib/canvas.js
Moves color lookup and hidden status out from being per pixel to being per label. Much faster!
> Faster segmentation masks

- backend/kangas/server/flask_server.py
- frontend/app/PagerBar/index.js
- frontend/app/PagerBar/pager.js
- frontend/pages/api/download.js
This is useful for hosted kangas services, like kangas.comet.com.
> Add a download datagrid link

- backend/setup.py
- frontend/app/Settings/RefreshButton.js
- frontend/app/cells/baseClient.js
- frontend/app/contexts/ViewContext.js
- frontend/lib/hooks/useDebounce.js
- frontend/lib/hooks/useQueryParams.js
Fixes https://github.com/comet-ml/kangas/issues/75
> Update boundary and begin on page refresh

- backend/kangas/__init__.py
- backend/kangas/datatypes/datagrid.py
This PR allows the Python SDK to pass server flags via dg.show() and kg.show().
> Allow server flags to be passed from show()

- backend/kangas/datatypes/datagrid.py
This PR allows user to use PosixPaths as filenames.
> Allow PosixPath as filenames

- backend/kangas/server/queries.py
> Update to fix kangas.comet.com server due to updated pillow

- backend/kangas/_version.py
- backend/kangas/datatypes/embedding.py
- backend/kangas/server/flask_server.py
- backend/kangas/server/queries.py
- backend/kangas/server/tasks.py
- backend/kangas/server/utils.py
- backend/setup.py
- frontend/app/cells/embedding/EmbeddingCellClient.js
This PR cleans up the PCA Projection, and adds t-SNE Projection via an argument to Emebedding().
> Embedding projections additions

- backend/kangas/datatypes/utils.py
- frontend/app/cells/image/ImageCanvas/OutputClient.js
- frontend/lib/canvas.js
This PR:
* moves all drawing routines to lib/canvas.js (just refactor)
* adds some transparency to regions
Before:
After:
> Refactored drawing functions

- backend/kangas/server/queries.py
- frontend/app/Settings/Buttons/ComputedColumnsButton.js
- frontend/app/modals/ComputedColumnsModal/ComputedColumnsEditor.js
- frontend/app/modals/ComputedColumnsModal/index.js
The goal was to create a drop-in replacement for the textarea. Currently, there is a loop between calling the callback, and updating the computed columns, so actually set the CC is disabled.
> WIP: create a column JSON editor

- frontend/app/cells/charts/category/CategoryClient.js
- frontend/app/cells/charts/histogram/HistogramClient.js
- frontend/app/cells/embedding/EmbeddingCellClient.js
This PR:
1. displays a message every time an embedding, history, or category chart is opened
2. displays a message when something is coped to clipboard
> Display messages for clipboard copies

- frontend/app/Settings/ReactAutoComplete.js
- frontend/app/modals/ComputedColumnsModal/ComputedColumnsEditor.js
- frontend/app/modals/ComputedColumnsModal/ExpressionEditor.js
- frontend/app/modals/ComputedColumnsModal/ExpressionEditor.module.scss
- frontend/app/modals/ComputedColumnsModal/index.js
Needs a couple of CSS tweaks, and then should be done.
> Add completions in cc expression editor

- frontend/app/PagerBar/pager.js
- frontend/app/Settings/MatrixSelectClient.js
- frontend/app/Table/TableClientWrapper.js
- frontend/app/Table/table.js
- frontend/app/contexts/LoadingContext.js
- frontend/app/contexts/ViewContext.js
- frontend/app/modals/SelectColumnDrowpdown/SelectColumnDropdown.js
quick and dirty loading overlay
> Loading Screen

- backend/kangas/__init__.py
- backend/kangas/datatypes/datagrid.py
- backend/kangas/kaggle_env.py
- backend/kangas/utils.py
> Kaggle environment support

- backend/kangas/datatypes/datagrid.py
- frontend/app/cells/Cell.module.scss
- frontend/app/cells/baseClient.js
- frontend/app/cells/charts/Charts.module.scss
- frontend/app/cells/float/BaseFloatCell.js
- frontend/app/cells/float/index.js
- frontend/app/cells/text/BaseTextCell.js
- frontend/app/cells/text/index.js
- frontend/lib/fetchAssetMetadata.js
- frontend/lib/fetchMetadata.js
Below, score and confidence have colormap applied; sorted by score:
> Added colored float cells indicating value in range

- backend/kangas/datatypes/embedding.py
- backend/kangas/server/queries.py
- backend/setup.py
This PR uses the transform computed when logged. No need to transform on the fly later. This is much faster.
> Refactored projections to compute transforms beforehand

- frontend/app/cells/Cell.module.scss
- frontend/app/cells/json/index.js
- frontend/app/cells/text/BaseTextCell.js
- frontend/app/cells/text/index.js
> Added ability to see large text fields
